export enum TipoExercicio {
  AQUECIMENTO = 'AQUECIMENTO',
  FORÇA = 'FORÇA',
  RESISTENCIA = 'RESISTENCIA',
  VELOCIDADE = 'VELOCIDADE',
  TECNICA = 'TECNICA',
  ACADEMIA = 'ACADEMIA',
  DESCANSO = 'DESCANSO'
}
